services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DOCKER=1
    volumes:
      - ./QuickTalk/db.sqlite3:/app/QuickTalk/db.sqlite3
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
