# Generated by Django 5.1.1 on 2024-09-18 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name'),
        ),
    ]
