# Generated by Django 5.1.1 on 2024-09-15 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Username'),
        ),
    ]
